WithTODO/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: %i[new create]
  resources :tasks
  resource :todos

  get 'tutorial', to: 'top#tutorial'
  get 'port', to: 'todos#index'
  get 'setting', to: 'top#setting'
  get 'signin', to: 'user_sessions#new'
  post 'signin', to: 'user_sessions#create'
  delete 'signout', to: 'user_sessions#destroy'

  root 'top#top'
end

WithTODO/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

WithTODO/app/models/category.rb
class Category < ApplicationRecord
  has_many :inventory
  has_many :tasks
end

WithTODO/app/models/foodlog.rb
class Foodlog < ApplicationRecord
  belongs_to :user
  belongs_to :todo
  belongs_to :category
end

WithTODO/app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

WithTODO/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user,dependent: :destroy

  validates :name, presence: true
end

WithTODO/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :tasklist
  belongs_to :category
  has_one :taskschedule, dependent: :destroy

  validates :name, presence: true
  validates :category, presence: true
  validates :open, presence: true
  
end

WithTODO/app/models/tasklist.rb
class Tasklist < ApplicationRecord
  belongs_to :user
  has_many :task, dependent: :destroy
end

WithTODO/app/models/taskschedule.rb
class Taskschedule < ApplicationRecord
  belongs_to :task
end

WithTODO/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  has_one :foodlog

  validates :name, presence: true
  validates :user_id, presence: true

end

WithTODO/app/models/todotalk.rb
class Todotalk < ApplicationRecord
end

WithTODO/app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_one :profile, dependent: :destroy
  has_one :foodlog, dependent: :destroy
  has_one :inventory, dependent: :destroy
  has_many :tasklist, dependent: :destroy
  has_many :todos, dependent: :destroy
  delegate :name, to: :profile

  after_create :set_todo_and_tasklist

  # password；最小で3文字以上必要（新規レコード作成もしくはcrypted_passwordカラムが更新される時のみ適応）
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }

  # password_confirmation：値が空でないこと・passwordの値と一致すること（新規レコード作成もしくはcrypted_passwordカラムが更新される時のみ適応）
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  
  # email：値が空でないこと・ユニークな値であること
  validates :email, presence: true, uniqueness: true

  private

  def set_todo_and_tasklist
      todo = todos.create!(name:'名もなきトド')
      Tasklist.create!(user_id: self.id, todo_id: todo.id)
  end


end

WithTODO/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  def skip_header_footer
    @skip_header_footer = false
  end
end

WithTODO/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def index; end

  def show; end

  def new
    @task= Task.new
    @categories = Category.all
  end

  def create;
  end

  def destroy; end

  private

  def task_params
    params.require(:task).permit(:name, :contents, :open, :category_id, task_schedule_attributes: [:start_at, :end_at])
  end
end

WithTODO/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def show; end
end

WithTODO/app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :require_login, only: %i[top]

  def top
    @skip_header_footer = true
  end
  
  def setting; end

  def tutorial; end


end

WithTODO/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @skip_header_footer = true
  end

  def create
    @skip_header_footer = true
    @user = login(params[:email], params[:password])
    if @user
      flash[:success] ='ログインに成功しました'
      redirect_to tasks_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other #あとでさよなら画面に変える
  end
end

WithTODO/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @skip_header_footer = true
    @user = SignupForm.new
  end

  def create
    @skip_header_footer = true
    @user = SignupForm.new(signup_params)
    if @user.save
      redirect_to tasks_path, success: 'ユーザー登録が完了しました'
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new,status: :unprocessable_entity
    end
  end

  private

  def signup_params
    params.require(:signup_form).permit(:name, :email, :password, :password_confirmation)
  end
end

WithTODO/app/helpers/application_helper.rb
module ApplicationHelper
end

WithTODO/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithTODO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>

    <% unless @skip_header_footer %>
      <%= render 'shared/header'%>
    <% end %>

    <%= render 'shared/flash' %>

    <%= yield %>

    <% unless @skip_header_footer %>
      <%= render 'shared/footer'%>
    <% end %>

  </body>
</html>

WithTODO/app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

WithTODO/app/views/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

WithTODO/app/views/shared/_footer.html.erb
<div class='container-fluid d-flex fixed-bottom text-center text-white bg-todo'>
  <div class='container'>
    <%= link_to tasks_path, class:'text-white' do %>
      <i class="bi bi-clipboard-check"  style="font-size: 3rem;"></i>
    <% end %>
  </div>
  <div class='container'>
    <%= link_to todos_path, class:'text-white' do %>
      <i class="bi bi-emoji-smile" style="font-size: 3rem;"></i>
    <% end %>
  </div>
  <div class='container'>
    <%= link_to port_path, class:'text-white' do %>
      <i class="bi bi-cloud-haze"  style="font-size: 3rem;"></i>
    <% end %>
  </div>
  <div class='container'>
    <%= link_to setting_path, class:'text-white' do %>
      <i class="bi bi-wrench"  style="font-size: 3rem;"></i>
    <% end %>
  </div>
</div>

WithTODO/app/views/shared/_header.html.erb
<div class='container-fluid'>
  <div class='row mt-3 mb-1'>
    <div class='col'>
      <%= image_tag 'logo.png', size:'75x56', class:'text-start' %>
      <% if current_user.nil?%>
        誰もいないよ
      <% else %>
        <%= current_user.name %>がログイン中
      <% end %>
    </div>
    <div class='col text-end'>
      <%= link_to '使い方', tutorial_path, class: 'btn btn-light'%>
      <%= link_to 'サインアウト', signout_path, data: {turbo_method: :delete, turbo_confirm: 'サインアウトする？' }, class: 'btn btn-light' %>
    </div>
  </div>

WithTODO/app/views/tasks/_task.html.erb
<div class="card mb-3">
  <div class="card-header ">
    カテゴリ
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to 'タスクタイトル', task_path(1)%></h5>
    <div class="card-text">報酬</div>
    <div class='text-end'>
      <%= link_to ('#') do %>
      <i class="bi bi-check-square"  style="font-size: 3rem;"></i>
    <% end %>
    </div>
  </div>
</div>

WithTODO/app/views/tasks/index.html.erb
<div class='container-fulid bg-sky h-50vh text-center bg-img'>
  <div class='container d-flex justify-content-center h-100', style='width:600px;'>
    <div class='row '>
      <div class='col-5'>
          <div class="card mt-5">
            <div class="card-header ">
              とどじろー
            </div>
            <div class="card-body">
              <p class="card-text">しゃべる</p>
            </div>
          </div>
      </div>
      <div class='col-7 align-self-end'>
        <%= image_tag 'TODO.png', size:'500x500', class:'img-fluid' %>
      </div>
    </div>
  </div>
</div>

<div class='container-fluid'>
  <div class='container mt-3'>
    タスク一覧
    <div class='text-end mb-3'><%= link_to 'タスク追加', new_task_path, class:'btn btn-light' %></div>
  </div>
  <div class='container mb-5 pb-5'>
    <% 8.times do %>
      <%= render 'task'%>
    <% end %>
  </div>
 </div>

WithTODO/app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-lg-8 mx-auto">
      <h1>タスク作成</h1>
      <%= form_with model: @task do |f| %>
        <%= render 'shared/error', object: f.object %>
        <div class="mb-3">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :contents, class: "form-label" %>
          <%= f.text_area :contents, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :open, class: "form-label" %>
          <%= f.check_box :open %>
        </div>
        <div class="mb-3">
          <%= f.label :category_id, class: "form-label" %>
          <%= f.collection_select :caategory_id, @categories, :id, :name, class: "form-control" %>
        </div>
        <div class='mb-3'>
          <%= f.fields_for :taskschedule do |schedule_fields| %>
            <%= schedule_fields.label :start_at %>
            <%= schedule_fields.datetime_select :start_at %>
            <%= schedule_fields.label :end_at %>
            <%= schedule_fields.datetime_select :end_at %>
          <% end %>
        </div>
        <div class='text-end'>
        <%= f.submit "保存", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

WithTODO/app/views/tasks/show.html.erb
タスク詳細画面

WithTODO/app/views/todos/_food.html.erb
<div class='container w-50 mt-3'>
  ごはん
</div>

WithTODO/app/views/todos/index.html.erb
トドいっぱいいる画面

WithTODO/app/views/todos/show.html.erb
<div class='container-fulid bg-sky h-50vh text-center bg-img'>
  <div class='container d-flex justify-content-center h-100', style='width:600px;'>
    <div class='row '>
      <div class='col-5'>
          <div class="card mt-5">
            <div class="card-header ">
              とどじろー <%= link_to '#', class:'text-dark' do %><i class="bi bi-pencil"></i><% end %>
            </div>
          </div>
      </div>
      <div class='col-7 align-self-end'>
        <%= image_tag 'TODO.png', size:'500x500', class:'img-fluid' %>
      </div>
    </div>
  </div>
</div>

<div class='container-fluid'>
  <div class='container mt-3'>
    満腹度メーター  友好度メーター
  </div>
  <div class='container mb-5 pb-5 d-flex flex-wrap'>
    <% 6.times do %>
      <%= render 'food' %>
    <% end %>
  </div>
  <div class='container text-center'>
    <%= link_to '旅に送り出す', '#', class: 'btn btn-danger'%>
  </div>
 </div>

WithTODO/app/views/top/setting.html.erb
設定画面

WithTODO/app/views/top/top.html.erb
<div class='continer h-full m-5'>
  <div class='container text-center pt-5 h-50 bg-white'>
      <div class='row'>
        <div class='col'>
          トドと一緒に習慣化
        </div>
    </div>
    
    <div class='row'>
      <div class='col'>
      <%= image_tag 'logo.png', size:'300x225', class:'' %>
      </div>
    </div>
    <div class='row'>
      <div class='container text-center mt-3'>
        <%= link_to 'サインアップ', new_user_path,class:'btn btn-primary'%>
        <%= link_to 'サインイン', signin_path,class:'btn btn-primary'%>
      </div>
    </div>
  </div>

  <div class='container'>
    <div class='container text-light'>
      <div class='row'>
        <div class='col mt-5 text-dark bg-soft rounded-3 mb-5'>
          <h2 class='animate__rubberBand display-4 mb-3'>WithToDoって？</h2>
          <h3 class='animate__rubberBand text-end mb-3'>WithToDoは、トドの育成を通じてあなたの習慣化をサポートするアプリです</h3>
          <div class='col text-end'>
            <%= image_tag 'TODO.png', size:'300x300', class:'img-fluid' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

WithTODO/app/views/top/tutorial.html.erb
使い方紹介

WithTODO/app/views/user_sessions/new.html.erb
<div class='container mt-5 d-flex justify-content-center align-items-center'>
  <div class='row'>
    <div class='col'>
      <div class='card'>
        <div class='card-header'>
          サインイン
        </div>
        <div class='card-body'>
          <%= form_with url: signin_path, data: { turbo: false } do |f|%>
            <div class='mb-3'>
              <%= f.label :email, t('signup_form.email')%>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class='mb-3'>
              <%= f.label :password, t('signup_form.password')%>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class='text-end'>
              <%= f.submit 'サインイン',class: 'btn btn-primary'%>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

WithTODO/app/views/users/new.html.erb
<div class='container mt-5 d-flex justify-content-center align-items-center'>
  <div class='row'>
    <div class='col'>
      <div class='card'>
        <div class='card-header'>
          サインアップ
        </div>
        <div class='card-body'>
          <%= form_with model: @user, scope: :signup_form, url: users_path, data: { turbo: false } do |f|%>
            <%= render 'shared/error', object: f.object %>
            <div class='mb-3'>
              <%= f.label :name, t('signup_form.name')%>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class='mb-3'>
              <%= f.label :email, t('signup_form.email')%>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class='mb-3'>
              <%= f.label :password, t('signup_form.password')%>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class='mb-3'>
              <%= f.label :password_confirmation, t('signup_form.password_confirmation')%>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div class='text-end'>
              <%= f.submit 'サインアップ',class: 'btn btn-primary'%>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>